accounts/urls.py
from django.conf.urls import url

from accounts.views import persona_login
from django.contrib.auth.views import logout

urlpatterns = [
    url(r'login$', persona_login, name='persona_login'),
    url(r'logout$', logout, {'next_page': '/'}, name='logout'),
]

lists/urls.py
from django.conf.urls import url

from lists.views import new_list, view_list, my_lists

urlpatterns = [
    url(r'^(\d+)/$', view_list, name='view_list'),
    url(r'^new$', new_list, name='new_list'),
    url(r'^users/(.+)/$', my_lists, name='my_lists')
]

superlists/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from lists.views import home_page

urlpatterns = [
        url(r'^$', home_page, name='home'),
        url(r'^lists/', include('lists.urls')),
        url(r'^accounts/', include('accounts.urls')),
        url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ]

accounts/models.py
from django.db import models
from django.utils import timezone


class User(models.Model):
    email = models.EmailField(primary_key=True)
    last_login = models.DateTimeField(default=timezone.now)
    REQUIRED_FIELDS = ()
    USERNAME_FIELD = 'email'
    is_authenticated = True  # changed to property from method to avoid security warning
    is_anonymous = False

    # class Meta:
    #     db_table = 'accounts_user'

lists/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.conf import settings


class List(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

    @property
    def name(self):
        return Item.objects.filter(list_id=self.id).first().text

    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

lists/forms.py
from django import forms
from django.core.exceptions import ValidationError

from lists.models import Item, List

EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ItemForm(forms.models.ModelForm):
    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg',
            }),
        }
        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }


class NewListForm(ItemForm):
    def save(self, owner):
        if owner.is_authenticated:
            return List.create_new(first_item_text=self.cleaned_data['text'], owner=owner)
        else:
            return List.create_new(first_item_text=self.cleaned_data['text'])


class ExistingListItemForm(ItemForm):
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

accounts/views.py
from django.contrib.auth import login
from django.http import HttpResponse

from accounts.authentication import PersonaAuthenticationBackend


def persona_login(request):
    assertion = request.POST['assertion']
    persona_backend = 'accounts.authentication.PersonaAuthenticationBackend'
    user = ''
    pab = PersonaAuthenticationBackend()
    try:
        user = pab.authenticate(assertion=assertion)
    except Exception as e:
        print('Persona authentication didnt work. Error: {0}'.format(e))
    if user:
        login(request, user, backend=persona_backend)
    return HttpResponse('OK')

lists/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import redirect, render

User = get_user_model()

from lists.forms import ExistingListItemForm, ItemForm, NewListForm
from lists.models import List


def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})


def new_list(request):
    form = NewListForm(data=request.POST)
    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)
    return render(request, 'home.html', {'form': form})


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, 'list.html', {'list': list_, "form": form})


def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, 'my_lists.html', {'owner': owner})

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>To-Do lists</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" media="screen">
    <link rel="stylesheet" href="{% static "css/base.css" %}" media="screen">
</head>
<body>
<div class="container">
    <div class="navbar navbar-default" role="navigation">
        <a href="/" class="navbar-brand">Superlists</a>
        {% if user.email %}
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'my_lists' user.email %}">My lists</a>
                </li>
            </ul>
            <a href="{% url 'logout' %}" class="btn navbar-btn navbar-right" id="id_logout">Log out</a>
            <span class="navbar-text navbar-right">Logged in as {{ user.email }}</span>
        {% else %}
            <a href="#" class="btn navbar-btn navbar-right" id="id_login">Sign in</a>
        {% endif %}
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3 jumbotron">
            <div class="text-center">
                <h1>{% block header_text %}{% endblock %}</h1>

                {% block list_form %}
                    <form method="post" action="{% block form_action %}{% endblock %}">
                        {{ form.text }}
                        {% csrf_token %}
                        {% if form.errors %}
                            <div class="form-group has-error">
                                <div class="help-block">{{ form.text.errors }}</div>
                            </div>
                        {% endif %}
                    </form>
                {% endblock %}
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block table %}{% endblock %}
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block extra_content %}
            {% endblock %}
        </div>
    </div>
</div>
<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'js/persona.js' %}"></script>
<script src="{% static 'accounts.js' %}"></script>
<script src="{% static 'js/list.js' %}"></script>
<script>
    $(document).ready(function () {
        var user = "{{ user.email }}" || null;
        var token = "{{ csrf_token }}";
        var urls = {
            login: "{% url 'persona_login' %}",
            logout: "{% url 'logout' %}"
        };
        Superlists.Accounts.initialize(navigator, user, token, urls);
    });
</script>
</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
            <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>
{% endblock %}

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %}My lists{% endblock %}

{% block list_form %}{% endblock %}

{% block extra_content %}
    <h2>{{ owner.email }}'s lists</h2>
    <ul>
        {% for list in owner.list_set.all %}
            <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}